### ISSUE TITLE
Create dedicated class or method for command line parse

### ISSUE THREAD

**Issue by dmakushin** [makarxiv/test_task#1]
Please, refer the link
https://github.com/makarxiv/test_task/blob/ba86b1e008866513e7b12311a9bd0ba4ec5759de/test/test.cpp#L26-L67

Let's create one more structure
```
struct CommandLineProperties
{
	bool log_enabled;
	std::string mode;
	std::string input_file_name; 
	std::string log_file_name;
};
```

And method which input are command line parameters and output is newly created structure
```
CommandLineProperties ParseCommandLine(argc, argv) {...}
```

**Comment by makarxiv** [comment]
include in start_commit
