### ISSUE TITLE
Replace ret codes to exceptions

### ISSUE THREAD

**Issue by dmakushin** [makarxiv/test_task#2]
https://github.com/makarxiv/test_task/blob/ba86b1e008866513e7b12311a9bd0ba4ec5759de/test/xslxDir.cpp#L82-L100

Replace all the ret code occurrences across the project to exceptions.

Example of how to create own exceptions
http://www.cplusplus.com/doc/tutorial/exceptions/

And examples of exceptions usage
https://www.tutorialspoint.com/cplusplus/cpp_exceptions_handling.htm

**Comment by makarxiv** [comment]
include in "Add exeptions for errors reading files" commit
